version: '3.8'

networks:
  default:

services:
  elasticsearch:
    build:
      context: ./
      dockerfile: ./Dockerfile-elastic
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
  kibana:
    container_name: kibana
    image: kibana:6.5.3
    platform: linux/amd64
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch 
volumes: 
  mysql-volume:
  redis-data:
  es_data:
